#+TITLE: The Book of Sidrach

* Introduction
/Le Livre de Sydrach le philosophe/ is an anonymous encyclopedic text written in Old French (or possibly Provençal) in the late thirteenth century and later translated into multiple European languages, including Middle Low German and Old Danish.

The work is written as a dialogue between the Babylonian king /Boctus/ and a wise philosopher named /Sidrach/ (/Sydrak/, etc.). It is reminiscent of other encyclopedic dialogues such as the twelfth-century /Lucidarius/, compiled under the auspices of Henry the Lion (/Heinrich der Löwe/) in Braunschweig, ca. 1190.

The French text of /Sidrach/ was translated into multiple European languages, including Italian (14th cent.), Dutch (14th?) and English (15th). A Low German translation is preserved in full in a manuscript from the end of the fifteenth century as well as a fragment from the sixteenth. Both manuscripts are held in and were possibly even produced in Denmark. A Danish translation preserved in a manuscript from the second half of the fifteenth century likely derives from the Low German translation.

* Meister Sydracks Bock (Low German)
[[https://handrit.is/manuscript/view/en/AM04-0807/0#mode/2up][Copenhagen, Den Arnamagnæanske Samling, AM 807 4to]] is a parchment manuscript containing the /Book of Sidrach/ in Low German. According to a [[https://handrit.is/manuscript/view/en/AM04-0807/307?iabr=on#page/152v/mode/2up][colophon at the end of the manuscript (f. 152v)]], it was written "To copenhauen na godes ghebort dusent vierhundert also vort in dem LXXIX Jaer" (in Copenhagen, 1479). 

The text opens with a list of the 387 questions which King Boctus poses to Sidrach, while the [[https://handrit.is/manuscript/view/en/AM04-0807/27?iabr=on#page/12v/mode/2up][main text begins on f. 13r]].

Árni Magnússon bought the manuscript from the auction of Frederik Rostgaard in 1726.

A fragment of the Low German /Sidrach/ is found in the manuscript Copenhagen, Det Kgl. Bibliotek, NKS 285 fol. The mansucript was produced in the sixteenth century and belonged to P. F. Suhm, whose collection entered the Royal Library in 1798.

The Low German translation of /Sidrach/ was [[https://archive.org/details/dasbuchsidrachn00jellgoog/mode/2up][edited in 1904 by H. F. Jellinghaus]].

* Sydrak (Danish)
Copenhagen, Det Kgl. Bibliotek, NKS 236 is a fifteenth-century paper manuscript containing the /Book of Sidrach/ in Danish. As with the fragmentary manuscript NKS 285 fol., this manuscript belonged to P. F. Suhm.

The Danish manuscript was edited by Gunnar Knudsen in 1921.
